version: '3.7'

services:
  certbot:
    build:
      context: ./certbot
    env_file:
      - ./certbot/.env
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nestjs-server
    networks:
      - Qnote_network

  nestjs-server:
    build:
      context: ./
      dockerfile: dockerfile.prod
    container_name: nestjs-server
    # ports:
    #   - '3000:3000'
    networks:
      - Qnote_network
    environment:
      - NODE_ENV=production
      - MYSQL_DATABASE_SYNCHRONIZE=false
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - '3306:3306'
    networks:
      - Qnote_network

networks:
  Qnote_network:
    driver: bridge
