services:
  nestjs-server:
    build:
      context: ./
      dockerfile: dockerfile.dev
    container_name: nestjs-server
    ports:
      - '3000:3000'
    networks:
      - Qnote_network
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - MYSQL_DATABASE_SYNCHRONIZE=true
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - Qnote_network

networks:
  Qnote_network:
    driver: bridge
